import type { NextPage } from "next";
import Head from "next/head";
import { Tabs, TabList, Tab, Checkbox, Button, TabPanel, TabPanels, TextInput, Accordion, AccordionItem } from '@carbon/react';
import { string } from "zod";

export interface ListProps {
  name: string;
  email: string;
  phone: string;
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Tabs>
          <TabList
            aria-label="List of tabs"
            contained
          >
            <Tab>
              Contacts
            </Tab>
            <Tab>
              Add Contact
            </Tab>
            <Tab>
              Account
            </Tab>
          </TabList>
          <TabPanels>
            <TabPanel>
              <ContactList 
                name="John Doe"
                email="test@email.com"
                phone="+1 (123)456-7890"
              />
            </TabPanel>
            <TabPanel>
              <form
                style={{
                  margin: '2em'
                }}
              >
                <legend className="cds--label">
                  Validation example
                </legend>
                <Checkbox
                  id="cb"
                  labelText="Accept privacy policy"
                />
                <Button
                  style={{
                    marginBottom: '1rem',
                    marginTop: '1rem'
                  }}
                  type="submit"
                >
                  Submit
                </Button>
                <TextInput
                  helperText="Optional help text"
                  labelText="Text input label"
                  type="text"
                />
              </form>
            </TabPanel>
            <TabPanel>
              Tab Panel 3
            </TabPanel>
          </TabPanels>
        </Tabs>
      </main>
    </>
  );
};

const ContactList = ({name, email, phone}: ListProps) => {
  return (
    <Accordion align="start">
      <AccordionItem title={name}>
        <p>{email}</p>
        <p>{phone}</p>
      </AccordionItem>
    </Accordion>
  )
}

export default Home;
